### ISSUE TITLE
设置默认打开

### ISSUE THREAD

**Issue by zhaoxin-wen** [no5ix/auto-toc#2]
你好，非常感谢你插件。请问是否可以添加一个功能，设置默认每一个网站都使用目录功能。非常感谢

**Comment by no5ix** [comment]
有开关的哈, 最新版本增加了两个 **高级技巧**: 
- 单击 TOC拖动栏 可以自动折叠 TOC
- 双击 TOC拖动栏 可以关闭 TOC
