### ISSUE TITLE
微信文章显示效果

### ISSUE THREAD

**Issue by anyiweb** [no5ix/auto-toc#4]
您好，对微信文章的支持好像有问题，显示不出来
<img width="166" alt="image" src="https://user-images.githubusercontent.com/60560420/232230433-5d57b1f3-6916-4521-a942-82d7dec9adf1.png">

**Comment by no5ix** [comment]
目前主要支持这几种 HTML label来作为标题哈:
H1, H2, H3, H4, H5, H6
<strong>
<b>

微信的标题每个公众号都用各种不同的东西来当标题, 有些是图片有些就是普通的正文加大了, 不好识别, 太乱了

**Comment by no5ix** [comment]
目前支持了一些文本加粗的居中的标题识别以及会自动提取空标题相邻的文本作为标题, 微信公众号有挺多是这样的, 算是支持了一大部分吧, 比如你给的这个链接的公众号文章, 已经可以很好的识别了
