### ISSUE TITLE
github上不能用

### ISSUE THREAD

**Issue by BoltLi** [no5ix/auto-toc#5]
如题，github这么重要的居然不能用，有些懵圈，其他很多网站都能用。希望修一下这个bug

**Comment by no5ix** [comment]
哈? 可以用啊, 给个具体的网址我看看哪个不能用

**Comment by no5ix** [comment]
![image](https://github.com/no5ix/auto-toc/assets/10043156/3a420393-4094-4698-96f4-0ddf9485db8a)
github这不是正常的吗?

**Comment by BoltLi** [comment]
> 哈? 可以用啊, 给个具体的网址我看看哪个不能用

之前不行，现在我这边也可以用了，也许是我按装的其他一些插件和这个冲突了。不过也发现下面这个网址只有标题的没有被识别出来
https://github.com/Robin-Haupt-1/Obsidian-Map-of-Content#map-of-content-for-obsidian

**Comment by no5ix** [comment]
> > 哈? 可以用啊, 给个具体的网址我看看哪个不能用
> 
> 之前不行，现在我这边也可以用了，也许是我按装的其他一些插件和这个冲突了。不过也发现下面这个网址只有标题的没有被识别出来 https://github.com/Robin-Haupt-1/Obsidian-Map-of-Content#map-of-content-for-obsidian

这个文章只有一个标题, 没必要显示了吧 :)

**Comment by BoltLi** [comment]
> 这个文章只有一个标题, 没必要显示了吧 :)


这其实反映出这个脚本还有些地方还是不够到位，像有些有几个都没法识别，感觉最好还是能够全显示出来，或者给选择显示哪些标题的权利（例如markdown现在的6级标题）
例如下面这个就有两个没法显示
https://github.com/juqkai/obsidian-proxy-github#obsidian-%E7%A4%BE%E5%8C%BA%E6%8F%92%E4%BB%B6%E4%B8%8B%E8%BD%BD%E4%BF%AE%E5%A4%8D
![QQ截图20230907113605](https://github.com/no5ix/auto-toc/assets/42888380/a2d93ff5-564c-4130-876f-67e2f17a38e2)

**Comment by no5ix** [comment]
> > 这个文章只有一个标题, 没必要显示了吧 :)
> 
> 这其实反映出这个脚本还有些地方还是不够到位，像有些有几个都没法识别，感觉最好还是能够全显示出来，或者给选择显示哪些标题的权利（例如markdown现在的6级标题） 例如下面这个就有两个没法显示 https://github.com/juqkai/obsidian-proxy-github#obsidian-%E7%A4%BE%E5%8C%BA%E6%8F%92%E4%BB%B6%E4%B8%8B%E8%BD%BD%E4%BF%AE%E5%A4%8D ![QQ截图20230907113605](https://user-images.githubusercontent.com/42888380/266196712-a2d93ff5-564c-4130-876f-67e2f17a38e2.png)

这其实故意不显示的, 其实每个要显示的heading都是会打一个score, 如果那个heading 组成的group的score小于10就不显示, 因为页面很明显是看得出来, 比较典型的就是你给的这个网页的这种一二级标题都只有一个且组成一个heading group的情况

**Comment by no5ix** [comment]
算了我还是去掉这个打分吧, 免得还有其他人以为是bug  _(:з」∠)_

**Comment by BoltLi** [comment]
https://github.com/miaomiaosoft/PandaOCR
发现了，像这种还是有问题的，只显示标题，其他的小标题都不显示的。这种也还是挺常见的，希望也能适配下
